# Generated by Django 4.1.2 on 2022-11-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_min_cost__gte_0_product_max_cost__gte_0_and_more'),
        ('product_cost', '0003_remove_productcost_cost__gte_min_cost_and__lte_max_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
