# Generated by Django 4.1.2 on 2022-11-12 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_min_cost__gte_0_product_max_cost__gte_0_and_more'),
        ('product_cost', '0004_alter_productcost_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
