# Generated by Django 4.1.2 on 2022-11-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('min_cost__gte', 0)), name='min_cost__gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('max_cost__gte', 0)), name='max_cost__gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('min_cost__lte', models.F('max_cost'))), name='min_cost__lte_max_cost'),
        ),
    ]
