# Generated by Django 4.1.2 on 2022-11-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_min_cost__gte_0_product_max_cost__gte_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
