# Generated by Django 4.1.2 on 2022-11-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entity_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_email',
            field=models.CharField(max_length=250),
        ),
    ]
