# Generated by Django 4.1.2 on 2022-11-14 00:33

from django.db import migrations, models
import utils.json_encoder


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_entity_id_alter_event_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(encoder=utils.json_encoder.CustomJSONEncoder),
        ),
    ]
